local dap = require("dap")
local dapui = require("dapui")

vim.keymap.set("n", "<Up>", function ()
    dap.continue()
end)
vim.keymap.set("n", "<Down>", function ()
    dap.step_over()
end)
vim.keymap.set("n", "<Right>", function ()
    dap.step_into()
end)
vim.keymap.set("n", "<Left>", function ()
    dap.step_out()
end)
vim.keymap.set("n", "<leader>b", function ()
    dap.toggle_breakpoint()
end)
vim.keymap.set("n", "<leader>B", function ()
    dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
end)
vim.keymap.set("n", "<leader>lp", function ()
    dap.set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
end)
vim.keymap.set("n", "<leader>dr", function ()
    dap.repl.open()
end)
vim.keymap.set("n", "<leader>rc", function ()
    dap.run_to_cursor()
end)

vim.keymap.set("n", "<leader><Left>", function ()
    dapui.toggle(1)
end)
vim.keymap.set("n", "<leader><Down>", function ()
    dapui.toggle(2)
end)

