vim.keymap.set("n", "<leader>ps", function()
    require('telescope.builtin').live_grep()
end)
vim.keymap.set("n", "<C-p>", function()
    require('telescope.builtin').git_files()
end)
vim.keymap.set("n", "<Leader>pf", function()
    require('telescope.builtin').find_files()
end)

vim.keymap.set("n", "<leader>pw", function()
    require('telescope.builtin').grep_string({ search = vim.fn.expand("<cword>") })
end)
vim.keymap.set("n", "<leader>pb", function()
    require('telescope.builtin').buffers()
end)
vim.keymap.set("n", "<leader>vh", function()
    require('telescope.builtin').help_tags()
end)

vim.keymap.set("n", "<leader>rv", function ()
    require("telescope").extensions.file_browser.file_browser()
end)

vim.keymap.set("n", "<leader>pv", "<cmd>Telescope file_browser path=%:p:h<CR>")
